import { DEFAULT_PILOT_OFFERS } from "../pages/PilotManagement";

export const DEFAULT_CHALLENGES = [
  {
    id: "demo-ch-1",
    title: "AI-Powered Predictive Maintenance for Track Infrastructure",
    department: "Ministry of Railways",
    sector: "Deep Tech",
    budget: "₹2.5 Cr",
    deadline: "2026-10-15",
    problem_statement: "Autonomous inspection of rail track anomalies using computer vision models mounted on inspection locomotives.",
    description: "Seeking deep tech startups with computer vision models for real-time crack detection.",
    expected_outcome: "Zero-derailment target via continuous automated ultrasonic and visual rail anomaly reporting.",
    eligibility: "DPIIT Recognized Startups with TRL-6+ technology",
    location: "Pan-India / Northern Railway Division",
    status: "Published",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  {
    id: "demo-ch-2",
    title: "Autonomous Surveillance for Strategic Perimeter Defence",
    department: "Ministry of Defence",
    sector: "Defence & Aerospace",
    budget: "₹1.2 Cr",
    deadline: "2026-11-30",
    problem_statement: "Autonomous perimeter surveillance and drone swarm threat detection under extreme weather conditions.",
    description: "Solar-powered thermal and optical sensor network with satellite telemetry for forward borders.",
    expected_outcome: "24/7 all-weather perimeter intrusion detection with automated counter-drone coordination.",
    eligibility: "Defence startups with indigenous electronics & aerospace hardware IP",
    location: "Forward Operations Logistics Hub, Western Sector",
    status: "Published",
    created_at: new Date(Date.now() - 14 * 86400000).toISOString()
  },
  {
    id: "demo-ch-3",
    title: "High-Efficiency Solid-State Battery Storage for Micro-Grids",
    department: "Ministry of Power & Renewable Energy",
    sector: "CleanTech & Renewable Energy",
    budget: "₹3.2 Cr",
    deadline: "2026-12-10",
    problem_statement: "Next-gen battery storage solutions with >92% round trip efficiency for remote micro-grids.",
    description: "Scaling solid state lithium battery technology for micro-grid energy storage.",
    expected_outcome: "Long-cycle life storage supporting remote border posts and rural micro-grids.",
    eligibility: "CleanTech companies with indigenous cell chemistry IP",
    location: "Ladakh & North-East High Altitude Grids",
    status: "Published",
    created_at: new Date(Date.now() - 20 * 86400000).toISOString()
  }
];

export const DEFAULT_STARTUP_PROFILE = {
  id: "demo-startup-apex-001",
  full_name: "Vikram Patel",
  organization_name: "ApexVision AI Labs",
  email: "vikram@apexvision.ai",
  phone: "+91 99887 76655",
  role: "startup",
  verification_status: "verified",
  dpiit_id: "DIPP94821",
  sector: "Deep Tech",
  description: "Computer vision and edge AI models for predictive maintenance of industrial transport infrastructure.",
  website: "https://apexvision.ai"
};

export const DEFAULT_APPLICATIONS = [
  {
    id: "demo-app-1",
    challenge_id: "demo-ch-1",
    startup_id: "demo-startup-apex-001",
    startup_name: "ApexVision AI Labs",
    contact_person: "Vikram Patel",
    solution_title: "RailVision AI Track Anomaly Detection System",
    solution_description: "Real-time edge computer vision model mounted on locomotives for micro-fracture detection and automated GPS anomaly logging.",
    technology: "Edge AI (NVIDIA Jetson AGX), TensorRT, YOLO-Track, Sovereign Satellite Telemetry",
    expected_impact: "Reduce derailment risks by 84% and automate 25,000 km of manual track inspections.",
    timeline: "6 Months Pilot",
    estimated_cost: "₹1.50 Cr",
    status: "Shortlisted",
    eligibility_status: "eligible",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    challenges: DEFAULT_CHALLENGES[0]
  },
  {
    id: "demo-app-2",
    challenge_id: "demo-ch-2",
    startup_id: "demo-startup-garuda-002",
    startup_name: "Garuda Aerotech",
    contact_person: "Col. Raghavendra Joshi (Retd.)",
    solution_title: "GarudaNet Autonomous Edge Surveillance Grid",
    solution_description: "Solar-powered thermal and optical sensor network with satellite telemetry for forward perimeter defense.",
    technology: "Autonomous UAV Swarm, Thermal Optical Fusion, Mesh Network",
    expected_impact: "24/7 continuous border surveillance in zero-visibility conditions.",
    timeline: "3 Months Pilot",
    estimated_cost: "₹85 Lakh",
    status: "Under Review",
    eligibility_status: "eligible",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    challenges: DEFAULT_CHALLENGES[1]
  }
];

export const WORKFLOW_STAGES = [
  {
    step: 1,
    id: "challenge_proposal",
    title: "1. Propose Challenge",
    titleHi: "1. चुनौती प्रस्ताव",
    shortTitle: "1. Propose",
    shortTitleHi: "1. प्रस्ताव",
    role: "government",
    demoKey: "janparichay",
    badge: "Government",
    badgeHi: "सरकारी विभाग",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-200",
    description: "Ministry of Railways drafts & publishes sovereign problem statement with GFR budget.",
    caption: "Ministry posts railway vision challenge",
    captionHi: "रेल मंत्रालय ने रेलवे विजन चुनौती पोस्ट की",
    path: "/government/dashboard",
    state: { section: "challenges", openCreateModal: true },
    icon: "Landmark"
  },
  {
    step: 2,
    id: "startup_bid",
    title: "2. Startup Solution",
    titleHi: "2. स्टार्टअप समाधान",
    shortTitle: "2. Apply",
    shortTitleHi: "2. आवेदन",
    role: "startup",
    demoKey: "startup",
    badge: "Startup",
    badgeHi: "स्टार्टअप",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-200",
    description: "ApexVision AI Labs submits deep tech computer vision proposal & architectural approach.",
    caption: "ApexVision AI submits deep tech bid",
    captionHi: "एपेक्सविजन एआई ने डीप टेक बोली लगाई",
    path: "/startup/dashboard",
    state: { section: "challenges" },
    icon: "Rocket"
  },
  {
    step: 3,
    id: "ai_review",
    title: "3. Evaluation & Shortlist",
    titleHi: "3. मूल्यांकन एवं चयन",
    shortTitle: "3. Evaluate",
    shortTitleHi: "3. समीक्षा",
    role: "government",
    demoKey: "janparichay",
    badge: "Government",
    badgeHi: "सरकारी विभाग",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-200",
    description: "Inspect 92% AI compatibility matching, capability matrix, and shortlist applicant.",
    caption: "92% AI match & capability scoring",
    captionHi: "92% एआई मिलान और क्षमता स्कोरिंग",
    path: "/government/applications/demo-app-1",
    state: {},
    icon: "BrainCircuit"
  },
  {
    step: 4,
    id: "pilot_offer",
    title: "4. Pilot Offer & Contract",
    titleHi: "4. पायलट अनुबंध",
    shortTitle: "4. Contract",
    shortTitleHi: "4. अनुबंध",
    role: "government",
    demoKey: "janparichay",
    badge: "Govt & Startup",
    badgeHi: "विभाग व स्टार्टअप",
    badgeColor: "bg-purple-100 text-purple-800 border-purple-200",
    description: "Department issues formal pilot deployment offer with deliverables, ₹1.5 Cr budget & legal terms.",
    caption: "₹1.50 Cr grant & milestone schedule",
    captionHi: "₹1.50 करोड़ अनुदान और मील के पत्थर",
    path: "/pilot-management",
    state: {},
    icon: "FileCheck"
  },
  {
    step: 5,
    id: "live_pilot",
    title: "5. Live Pilot & Milestones",
    titleHi: "5. लाइव पायलट व टेलीमेट्री",
    shortTitle: "5. Milestones",
    shortTitleHi: "5. मील के पत्थर",
    role: "government",
    demoKey: "janparichay",
    badge: "Active Trial",
    badgeHi: "सक्रिय परीक्षण",
    badgeColor: "bg-cyan-100 text-cyan-800 border-cyan-200",
    description: "Hardware mounts calibrated, edge camera arrays transmitting, and milestones verified.",
    caption: "Edge cameras on 4 locomotives",
    captionHi: "4 रेल इंजनों पर एज कैमरे व सेंसर",
    path: "/pilot-management/demo-pilot-1",
    state: { tab: "milestones" },
    icon: "Target"
  },
  {
    step: 6,
    id: "completion_results",
    title: "6. Final Results & Completion",
    titleHi: "6. अंतिम परिणाम व पूर्णता",
    shortTitle: "6. Completion",
    shortTitleHi: "6. पूर्णता",
    role: "government",
    demoKey: "janparichay",
    badge: "Procurement Decision",
    badgeHi: "खरीद विस्तार निर्णय",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
    description: "Verify 94% defect accuracy, complete trial, and sign off recommendation for GeM scale-up.",
    caption: "94% accuracy certified & GeM scale-up",
    captionHi: "94% सटीकता प्रमाणित और GeM विस्तार",
    path: "/pilot-management/demo-pilot-1",
    state: { tab: "results", scrollToResults: true },
    icon: "Award"
  }
];

export const DEFAULT_PILOT_RESULT_1 = {
  pilot_offer_id: "demo-pilot-1",
  outcome: "94.2% defect detection accuracy achieved across 12,000 km of electrified railway track. 18 potential micro-fractures flagged and verified by permanent way inspectors ahead of scheduled manual walks.",
  success_metrics: "Zero false alarms exceeding threshold. Sub-190ms edge inference latency on NVIDIA Jetson AGX units. 100% telemetry uptime via GSAT satellite link.",
  kpi_actual: "94.2% Defect Accuracy (Target: >85%), 189ms Inference Latency",
  government_feedback: "Exceptional performance demonstrated under heavy monsoon and high-speed locomotive trials. Ministry technical committee certifies TRL-8 readiness.",
  kpi_target: "Minimum 85% anomaly precision across 10,000 track kilometers",
  final_recommendation: "scale",
  scale_up_pathway: "marketplace",
  validator_name: "Dr. Rajesh Kumar, Chief Track Engineer (Northern Railway)",
  validation_summary: "Approved for full GeM sovereign procurement framework across Northern and Western Railway zones.",
  validation_status: "passed",
  updated_at: new Date().toISOString()
};
