import { BrainCircuit, TrendingUp, Target, Zap, Globe, Clock, IndianRupee, Users, AlertTriangle } from "lucide-react";
import { scoreColor, scoreBgColor } from "../lib/utils";

const SCORE_LABELS = [
  { key: "problemFit", label: "Problem Fit", icon: Target },
  { key: "technicalFit", label: "Technical Fit", icon: Zap },
  { key: "impact", label: "Expected Impact", icon: TrendingUp },
  { key: "feasibility", label: "Feasibility", icon: BrainCircuit },
  { key: "timeline", label: "Timeline Fit", icon: Clock },
  { key: "budgetFit", label: "Budget Fit", icon: IndianRupee },
  { key: "capability", label: "Startup Capability", icon: Users },
];

export default function AIMatchPanel({ matchData, compact = false }) {
  if (!matchData) return null;

  const overall = matchData.overall_score ?? 0;

  if (compact) {
    return (
      <div className="flex items-center gap-2.5 text-xs text-slate-600">
        <span className="font-medium">AI Match:</span>
        <span className={`font-bold ${scoreColor(overall)}`}>{overall}%</span>
        <span className={`w-2 h-2 rounded-full ${scoreBgColor(overall).replace("bg-gradient-to-r ", "").replace(" from-", "bg-").replace(" to-", "")}`}></span>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-slate-50 via-white to-blue-50/30 rounded-2xl border-2 border-blue-100 shadow-sm overflow-hidden">
      <div className="bg-gradient-to-r from-[#0B192C] to-[#1E3E62] px-5 py-3.5 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <BrainCircuit className="w-5 h-5 text-amber-400" />
          <div>
            <h3 className="font-bold text-white text-sm" style={{ fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
              AI-Assisted Match Analysis
            </h3>
            <p className="text-xs text-slate-300 mt-0.5">Decision-support only — not an automated award</p>
          </div>
        </div>
        <div className="text-right">
          <div className="text-3xl font-extrabold text-white">{overall}%</div>
          <div className="text-[10px] text-slate-300">Overall Match</div>
        </div>
      </div>

      <div className="p-4">
        {/* Individual criterion scores */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
          {SCORE_LABELS.map(({ key, label, icon: Icon }) => {
            const val = matchData[key] ?? matchData.scores?.[key] ?? 0;
            const pct = Math.min(100, Math.round(val));
            return (
              <div key={key} className="space-y-1">
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-600 font-medium flex items-center gap-1">
                    <Icon className="w-3 h-3 text-slate-400" />
                    {label}
                  </span>
                  <span className={`font-bold ${scoreColor(pct)}`}>{pct}%</span>
                </div>
                <div className="w-full bg-slate-200 rounded-full h-1.5 overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all ${scoreBgColor(pct)}`}
                    style={{ width: `${pct}%` }}
                  />
                </div>
              </div>
            );
          })}
        </div>

        {/* Analysis text */}
        {matchData.analysis_text && (
          <div className="mb-3">
            <div className="flex items-center gap-1.5 mb-1.5">
              <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Why This Startup Matches
              </span>
            </div>
            <p className="text-xs text-slate-600 leading-relaxed whitespace-pre-line">
              {matchData.analysis_text}
            </p>
          </div>
        )}

        {/* Concerns */}
        {matchData.concerns_text && (
          <div className="border-t border-slate-200 pt-3">
            <div className="flex items-center gap-1.5 mb-1.5">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
              <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Potential Concerns
              </span>
            </div>
            <p className="text-xs text-slate-600 leading-relaxed whitespace-pre-line">
              {matchData.concerns_text}
            </p>
          </div>
        )}

        {/* Scorer version */}
        <div className="mt-3 pt-2 border-t border-slate-200 text-[10px] text-slate-400">
          Generated by: {matchData.scorer_version || "deterministic-mvp-v1"}
        </div>
      </div>
    </div>
  );
}
